name: Deploy to VPS

on:
  push:
    branches:
      - release/development

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            cd /home/rocky/projects/achini/uni-life-reborn
            git pull
            /home/rocky/.bun/bin/bun install
            /home/rocky/.bun/bin/bun run build
            /home/rocky/.bun/bin/pm2 restart uni-life

